name: my_app
description: Search City
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  drift: ^1.7.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  location: ^4.4.0
  path: ^1.8.1
  path_provider: ^2.0.0
  permission_handler: ^10.0.0
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.1.11
  drift_dev: ^1.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
